#!/bin/bash
#
# author: Sami Miaari
# e-mail: s.miaari@fz-juelich.de

#SBATCH --partition=batch
#SBATCH --nodes=1
#SBATCH --account=esmtst
#SBATCH --time=6:00:00
#SBATCH --job-name="pfsim"
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --mail-user=s.miaari@fz-juelich.de
#SBATCH --mail-type=ALL
#

export PARFLOW_DIR=/p/project1/cslts/miaari1/parflow/ParFlow_scripts/pfdir/install/
source /p/project1/cslts/miaari1/parflow/ParFlow_scripts/env_Stage2022_juwels.ini

cd /p/scratch/cslts/miaari1/infexfcases/test_case0
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case1
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case2
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case3
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case4
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case5
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case6
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case7
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case8
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case9
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case10
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case11
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case12
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case13
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case14
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case15
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case16
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case17
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case18
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case19
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case20
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case21
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case22
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case23
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case24
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case25
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case26
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case27
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case28
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case29
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case30
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case31
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case32
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case33
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case34
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case35
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case36
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case37
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case38
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case39
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case40
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case41
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case42
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case43
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case44
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case45
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case46
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case47
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case48
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case49
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case50
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case51
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case52
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case53
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case54
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case55
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case56
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case57
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case58
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case59
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case60
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case61
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case62
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case63
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case64
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case65
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case66
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case67
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case68
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case69
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case70
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case71
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case72
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case73
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case74
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case75
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case76
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case77
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case78
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case79
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case80
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case81
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case82
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case83
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case84
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case85
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case86
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case87
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case88
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case89
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case90
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case91
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case92
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case93
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case94
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case95
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case96
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case97
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case98
tclsh infiltration.tcl
tclsh exfiltration.tcl
cd /p/scratch/cslts/miaari1/infexfcases/test_case99
tclsh infiltration.tcl
tclsh exfiltration.tcl
